### ISSUE TITLE
Missing max_size attr_reader?

### ISSUE THREAD

**Issue by urfolomeus** [refile/refile-fog#1]
When using refile-fog with Rackspace I'm getting an `undefined method 'max_size' for #<Refile::Fog::Backend:0x007fddf21cccd0>` error. Looking through the code it looks like as though both [Refile::Backend::S3](https://github.com/elabs/refile/blob/master/lib/refile/backend/s3.rb) and [Refile::Backend::FileSystem ](https://github.com/elabs/refile/blob/master/lib/refile/backend/file_system.rb) have an attr_reader for max_size. Should this be set on [Refile::Fog::Backend](https://github.com/elabs/refile-fog/blob/master/lib/refile/fog.rb) too?

I'm happy to submit a patch if so.

**Comment by urfolomeus** [comment]
Actually, looking at the S3 backend it looks like things may have moved on interface-wise. I also had to add `extend Refile::BackendMacros` to [Refile::Fog::Backend](https://github.com/elabs/refile-fog/blob/master/lib/refile/fog.rb). Seems to be working (at least on first glance) other than that though. :)

How would you like to proceed with this? Are you looking to refactor Refile::Fog::Backend to be more like Refile::Backend::S3?

**Comment by brunoarueira** [comment]
I have the same issue, I'll send the PR to fix that

**Comment by jnicklas** [comment]
This has been fixed for a while, closing.
